import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useLazyLoadQuery } from "react-relay";
import { graphql } from "relay-runtime";
import styles from "../../styles/Home.module.css";
import { IssueButton } from "../components/IssueButton";
import { pagesIndexRepositoryNameQuery } from "./__generated__/pagesIndexRepositoryNameQuery.graphql";

const GitHubQuery = graphql`
  query pagesIndexRepositoryNameQuery($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
      __typename
      id
      name
    }
  }
`;

const Home: NextPage = () => {
  const data = useLazyLoadQuery<pagesIndexRepositoryNameQuery>(GitHubQuery, {
    owner: "ka2jun8",
    name: "relay-github",
  });

  if (!data || !data.repository) {
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>GraphQL Relay Sample</h1>

        <div>
          <h3>
            <Link href="/issues">/issues</Link>
          </h3>
          <br />
          <IssueButton repositoryId={data.repository.id} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
